### ISSUE TITLE
A directory error

### ISSUE THREAD

**Issue by riturajsoni** [MichalBusta/FASText#8]
hi
 I have run the program and install all the needed program. But when I run python evaluateSegmentation.py it gives the following error.
/home/rituraj/Downloads/FASText-master
Traceback (most recent call last):
  File "evaluateSegmentation.py", line 599, in <module>
    run_evaluation(inputDir, outputDir, process_color, processTest)
  File "evaluateSegmentation.py", line 35, in run_evaluation
    os.mkdir(outputDir)
OSError: [Errno 2] No such file or directory: '/home/busta/tmp/evalTest/2016-06-18'

Now I understands it that it requires the ICDAR 2013 data sets. I have that one also both train and test along with gt files downloaded from http://rrc.cvc.uab.es/ . 
1.  My question where I have to put my input directory. My FAST-master is present in 
/home/rituraj/Downloads
2. Will the output directory created by the code. 

Please suggest the solutions,
Regards

**Comment by riturajsoni** [comment]
What is the OSError :[ error no.2  coming

**Comment by MichalBusta** [comment]
Hello,

On 06/18/2016 12:54 PM, riturajsoni wrote:

> hi
> I have run the program and install all the needed program. But when I 
> run python evaluateSegmentation.py it gives the following error.
> /home/rituraj/Downloads/FASText-master
> Traceback (most recent call last):
> File "evaluateSegmentation.py", line 599, in
> run_evaluation(inputDir, outputDir, process_color, processTest)
> File "evaluateSegmentation.py", line 35, in run_evaluation
> os.mkdir(outputDir)
> 
> just modify outputBase or outputDir variable, to any directory you like.
> 
> OSError: [Errno 2] No such file or directory: 
> '/home/busta/tmp/evalTest/2016-06-18'
> 
> Now I understands it that it requires the ICDAR 2013 data sets. I have 
> that one also both train and test along with gt files downloaded from 
> http://rrc.cvc.uab.es/ .
> 1. My question where I have to put my input directory. My FAST-master 
> is present in
> /home/rituraj/Downloads
> 
> the expected input directory is in var inputDir.
> The code expect:
>      - in input directory _.jpg, gt__.txt files  from icdar 2013 dataset
>          - subdirectory "segmentations" with corresponding segmentations 
> from text segmentation challenge.
> 1. Will the output directory created by the code.
> 
> yes.

All the best, Michal

**Comment by riturajsoni** [comment]
thanks for the reply
 I did this with following files in the path
1. Input files : /textspotter/evaluation-sets/icdar2013-Test/img_1.jpg  
2. gt files in : /textspotter/evaluation-sets/icdar2013-Test/segmentations/img_1_GT.txt
3. .png files in : /textspotter/evaluation-sets/icdar2013-Test/segmentations/gt_img_1.png

The code all the files perfectly but a error occurs 
which is attached ..here the error 

```
octaves = np.unique( letterInside[:, 2])
```

   IndexError: too many indices

My question : What is this error. Am i placing the files in right folder becos thats what i understand from the code that it will get the gt file and then try to locate the .bmp files or .png files.
please suggest the solution
![results](https://cloud.githubusercontent.com/assets/16069242/16256165/ac7457a4-386d-11e6-85f9-b85652f6be45.png)

**Comment by MichalBusta** [comment]
You can go to debug mode or print the content of

|letterInside, lettersInside.shape|

**Comment by riturajsoni** [comment]
Hi michal
I did that it is printing
1. print letterInside
[ 466.94403076  131.07200623    3.          137.         -153.43495178
  466.94403076  139.26400757  458.75201416  126.97600555    1.            1.
    0.        ]
2. print letterInside.shape
(12,)

what does it mean...
thanks for the reply

**Comment by riturajsoni** [comment]
The letterInside seems to be single dimenson array therfore 
**octaves = np.unique( letterInside[:, 2])
IndexError: too many indice**

is coming .... the code get stucks here....share if you can help

**Comment by MichalBusta** [comment]
ust need simple fix may work:
- if len(letterInside) == 1:
           letterInside = np.reshape(1, letterInside.shape[0])

**Comment by riturajsoni** [comment]
1. len(letterInside) is coming 12 in present case...so it seems to one Dimensional matrix. What should be the size of the letterInside for the proper result. 
2. letterInside =  keypointsInside[rectMask, :]
   here rectMask is coming false....

**Comment by MichalBusta** [comment]
sorry typo:
     len(letterInside.shape)

**Comment by riturajsoni** [comment]
Thanks for suggestion although i change it a  bit 
1. if len(letterInside.shape) == 1: 
            letterInside = np.reshape(letterInside,(1,letterInside.shape[0])).T
that  gives the letterInside as [12,0] arrangement as simply reshape giving errors and also changes the octaves = np.unique( letterInside[:, 2]) to octaves = np.unique( letterInside[:, 0]) as the 2 was still out of index. 
now the new error occurs like this
  File "evaluateSegmentation.py", line 625, in <module>
    run_evaluation(inputDir, outputDir, process_color, processTest)
  File "evaluateSegmentation.py", line 248, in run_evaluation
    union_area = utils.area(utils.union(rectn, gt_rect))
  File "/home/rituraj/Downloads/FASText-master/tools/utils.py", line 28, in area
    width =a[2] - a[0]
TypeError: unsupported operand type(s) for -: 'str' and 'int'
what is happening here ...I am trying to figure out but not getting ho w to resolve it.

**Comment by riturajsoni** [comment]
thanks i write these lines and able to get (1,12) form 
1.   if len(letterInside.shape) == 1: 
           letterInside = np.reshape(letterInside, (1,letterInside.shape[0]),order='C')
       print letterInside.shape
   # the output of last statement is (1,12)
   #This is the output of the print letterInside
   [[ 466.94403076  131.07200623    3.          137.         -153.43495178
   466.94403076  139.26400757  458.75201416  126.97600555    1.            1.
   1.        ]]

so now again the  following error comes 
 File "evaluateSegmentation.py", line 626, in <module>
    run_evaluation(inputDir, outputDir, process_color, processTest)
  File "evaluateSegmentation.py", line 249, in run_evaluation
    union_area = utils.area(utils.union(rectn, gt_rect))
  File "/home/rituraj/Downloads/FASText-master/tools/utils.py", line 28, in area
    width =a[2] - a[0]
TypeError: unsupported operand type(s) for -: 'str' and 'int'

how to resolve this

**Comment by MichalBusta** [comment]
On 06/22/2016 12:56 PM, riturajsoni wrote:

> thanks i write these lines and able to get (1,12) form
> 1. if len(letterInside.shape) == 1: letterInside =
>    np.reshape(letterInside, (1,letterInside.shape[0]),order='C')
>    print letterInside.shape # the output of last statement is (1,12)
>    #This is the output of the print letterInside [[ 466.94403076
>    131.07200623 3. 137. -153.43495178 466.94403076 139.26400757
>    458.75201416 126.97600555 1. 1.
>    1. ]]
> 
> so now again the following error comes
> File "evaluateSegmentation.py", line 626, in
> run_evaluation(inputDir, outputDir, process_color, processTest)
> File "evaluateSegmentation.py", line 249, in run_evaluation
> union_area = utils.area(utils.union(rectn, gt_rect))
> File "/home/rituraj/Downloads/FASText-master/tools/utils.py", line 28, 
> in area
> width =a[2] - a[0]
> TypeError: unsupported operand type(s) for -: 'str' and 'int'
> 
> what is your gt format:

38, 43, 920, 215, "Tiredness"
275, 264, 665, 450, "kills"
0, 699, 77, 830, "A"
128, 705, 483, 839, "short"
542, 710, 938, 841, "break"
87, 884, 457, 1021, "could"
517, 919, 831, 1024, "save"
166, 1095, 468, 1231, "your"
530, 1069, 743, 1206, "life"

?

**Comment by riturajsoni** [comment]
yes this is the gt format and same image is taken for the experiment and i have taken this image only..for beginning once results will come i will put more in the folders. along with .jpg and gt.txt i have included .png file for it as per the code requirement.

**Comment by riturajsoni** [comment]
i try to check the type of 'a'  in the function utils.area it comes out be < tuple, tuple> 
#def area(a):
    '''Computes rectangle area'''

```
print type(a)       
#print a[1]
#print a[2] 
#print a[3]
a[1]=a[2] - a[0]
height=a[3] - a[1]
return width * height # 
```

I think the error lies here only...as tuple cannot be assigned a integer. as well as it is stated that the value of tuple cannot be changed as they are immutable objects.
Please suggest some solutions ...

**Comment by MichalBusta** [comment]
Hi,

On 06/23/2016 09:08 AM, riturajsoni wrote:

> i try to check the type of 'a' in the function utils.area it comes out 
> be < tuple, tuple>
> #def area(a):
> '''Computes rectangle area'''
> 
> |print type(a) #print a[1] #print a[2] #print a[3] a[1]=a[2] - a[0]|
> |the last version of github code is:

def area(a):
     '''Computes rectangle area'''
     width = a[2] - a[0]
     height = a[3] - a[1]
     return width \* height

however the inputs are already bad - there should be (x, y, w, h, ....) 
- can you trace the origin of the values coming into the fnc area?

|
|

**Comment by riturajsoni** [comment]
Ok I shall try those

**Comment by riturajsoni** [comment]
Hi
 I got it how the values are going in to the fnc area
the values are going like this 

Actually the output of utils.union(rectn, gt_rect) ::  (796, 791, '38,', '215,') in my example case...
and the line union_area = utils.area(utils.union(rectn, gt_rect)) calls the area function so the input to the area function is like these four parameters  (796, 791, '38,', '215,') in which 796 and 791 are integers and '38', and '215', are not integers.

Same also happening in the line around 280 union_area = utils.area(utils.union(rectn, chars2Rect))

I think this '38', and '215', are to be  converted in integer and it corresponds to a[2] and     a[3] in the area function.
Regards

**Comment by riturajsoni** [comment]
Hello
 I put the following code in utls.py file that solves the problem  of 38, to '38' etc.
 minX = minX.replace(',', '')
	maxX = maxX.replace(',', '')
	minY = minY.replace(',', '')
	maxY = maxY.replace(',', '')

**Comment by riturajsoni** [comment]
hi 
I just put the following code in utls.py just before the line
 gt_rectangles.append([minX, minY, maxX, maxY, splitLine[4], 0, 0] )
The code is 
        minX = minX.replace(',', '')
    maxX = maxX.replace(',', '')
    minY = minY.replace(',', '')
    maxY = maxY.replace(',', '')
that solve the problem of reading 38, as '38' and further adding the follwoing lines in utils.py 
width=int(a[2]) - int(a[0])
    height=int(a[3]) - int(a[1])
    return width \* height 
It therefore read the integer properly.

Now the error comes at this point 
Traceback (most recent call last):
  File "evaluateSegmentation.py", line 655, in <module>
    run_evaluation(inputDir, outputDir, process_color, processTest)
  File "evaluateSegmentation.py", line 299, in run_evaluation
    ratio = int_area / float(union_area)
ZeroDivisionError: float division by zero

it happens in the line r
ratio = int_area / float(union_area)

Please share if any solution is there.,

**Comment by riturajsoni** [comment]
Hi 
Sorry for late reply....The file is 
1- .Gt FILE
[img_1_GT.txt](https://github.com/MichalBusta/FASText/files/333206/img_1_GT.txt)
2. IMAGE FILE is 
![img_1](https://cloud.githubusercontent.com/assets/16069242/16358287/a564261c-3b2c-11e6-89df-77424d0697fb.jpg)
3. .PNG FILE IS
![gt_img_1](https://cloud.githubusercontent.com/assets/16069242/16358291/b85d6daa-3b2c-11e6-8e0e-3042f6afd89a.png)

These are the file ( only one image and its gt file and its .png file from ICDAR 2013 test set is used.)

Please check and guide me further.
Regards

**Comment by MichalBusta** [comment]
Hi,
one more check:
     - in attachment there are also segmentations gt files (for 
character level) - they should be located in "segmentations" subdir. 
(for some reason, they are now included just on Train set in ICDAR 
downloads).

Michal

**Comment by riturajsoni** [comment]
Yes the .gt files are present in the train section for character level segmentation but that are correspond to different set of images.
 Please tell me which set of images( .jpg, .gt , .png ) files should be put in directories to run the code.

**Comment by MichalBusta** [comment]
https://drive.google.com/file/d/0B8SUcdkLTcuTNTY0V09uT3B1ZGM/view?usp=sharing

**Comment by riturajsoni** [comment]
Ok I have downloaded these files and make this folder as the input file...
the results are coming like this.....
![figure_1](https://cloud.githubusercontent.com/assets/16069242/16544913/cae8c0a6-4134-11e6-9732-32ced8e5916e.png)
![figure_2](https://cloud.githubusercontent.com/assets/16069242/16544914/cf40b4e2-4134-11e6-8230-ea18666da227.png)

Can you show me how the results file look alike....

**Comment by riturajsoni** [comment]
The code line
        segmGt = '{0}/{1}_gt.txt'.format(segmDir, baseName)
suggests that the ground text should have *_gt.txt format . but the files present in the segmentation directory have *_GT.txt format. 
SO any changes have to be made in the code or input directory. I think I am very close to get the results. The folder contains both character segmentation ground text file and word segmented ground text file . Which file should be used.
 Please send how the results look alike.

**Comment by riturajsoni** [comment]
Can you please send how the result files will look like.. I am running code on the dataset shared by you..
Thanks

**Comment by riturajsoni** [comment]
I have run the code on the dataset shared by you but still some issues occur like..
THE SHAPE OF THE letterInside is after changing is : (1, 12)
Traceback (most recent call last):
  File "evaluateSegmentation.py", line 625, in <module>
    run_evaluation(inputDir, outputDir, process_color, processTest)
  File "evaluateSegmentation.py", line 244, in run_evaluation
    union_area = utils.area(utils.union(rectn, gt_rect))
  File "/home/rituraj/Downloads/FASText-master/tools/utils.py", line 30, in area
    width=a[2] - a[0]
TypeError: unsupported operand type(s) for -: 'str' and 'int'

This error is coming because of some typecasting problem... If i correct it then the following error occurs
 Traceback (most recent call last): File "evaluateSegmentation.py", line 655, in run_evaluation(inputDir, outputDir, process_color, processTest) File "evaluateSegmentation.py", line 299, in run_evaluation ratio = int_area / float(union_area) ZeroDivisionError: float division by zero 

Division by zero error.

I think I am trying but not able to excute this code...may be mistakes at my end.. If possible just tell me how the results ( any sample of results like graph, image anything) then possibly I can excute it.
Regards

**Comment by riturajsoni** [comment]
hi any help on the above issues if you can so that ..I can proceed further

**Comment by MichalBusta** [comment]
Hi,

the results are quite simple - program will print results to the console:

r          p         HMean        KP        M.Let.  M.Seg. SegC        RecR
0.799  0.147  0.473        753351   85.0     772.0       259885.0 0.867

Times:

KP           s                   c            rawCls   tl Wt       tc  
tt     StrSeg    GCTime
38.987  129.511002   46.236   1.876     0.0  0.169  0.0  0.0 28.399     0.0

the results are also stored in evaluation.npz

the problems you are reporting are still same - there is wrong parsing 
of gt files, so I'd recommend to put assert on gt file reading, 
something like:
assert type(value to check) is IntType - when assertation fails, you can 
look where the wrong entry came from, and add new assert to that point, 
so you can trace error quick.

P.S. sorry for delay, I have been on vacation.
